name: 'Commit Check'
on:
  push:

jobs:
  check-commit-message:
    name: Check Commit
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Format
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^((Merge pull request(.*))|(Release(.*))|(\[(feature|fix|doc|optimize|refactor|perf|test|chore)((\|)?(feature|fix|doc|optimize|refactor|perf|test|chore))?\][^\[\]]+))$'
          flags: 'gm'
          error: 'Please follow the commit style that the project.'