name: QodanaScan
on:
  push:
    branches:
      - dev
  
jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Cache
        uses: actions/cache@v3
        with:
          path: |
            build
            app/build
          key: ${{ runner.os }}-gradle-qodana-${{ hashFiles('*.gradle*', 'gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-qodana-
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2022.2.2
